# Generated by Django 2.2.6 on 2019-10-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgequestion',
            name='statement',
            field=models.ForeignKey(blank=True, help_text='qualification and unit selects are needed to reach statement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='categories.KnowledgeStatement', verbose_name='knowledge statement'),
        ),
    ]
