# Generated by Django 2.2.6 on 2019-10-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_reason', models.CharField(choices=[('FA', 'First application'), ('UB', 'Unit binding'), ('NC', 'New certificate')], max_length=2, verbose_name='application reason')),
                ('id_number', models.CharField(help_text='unique number for a person         like citizen id number, passport serial etc.', max_length=15, verbose_name='id code')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Unstated')], default='N', max_length=1, verbose_name='gender')),
                ('past_units', models.ManyToManyField(blank=True, related_name='students_pasts', to='categories.Unit', verbose_name='past units')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='categories.Qualification', verbose_name='qualification')),
                ('units', models.ManyToManyField(blank=True, related_name='students', to='categories.Unit', verbose_name='units')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
