# Generated by Django 2.2.6 on 2019-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamlog',
            name='result',
            field=models.CharField(blank=True, choices=[('S', 'Satisfactory'), ('U', 'Unsatisfactory'), ('N', 'Not Attended')], max_length=2, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='studentexamlog',
            name='units',
            field=models.ManyToManyField(related_name='student_exam_logs', to='categories.Unit', verbose_name='units'),
        ),
    ]
