# Generated by Django 2.2.9 on 2020-01-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('own_code', models.CharField(max_length=10, verbose_name='own code')),
                ('required', models.BooleanField(help_text='own_code prefixed by A are always required', verbose_name='is required')),
                ('exam_config', models.CharField(help_text='T1:60:10:60,120 means T1 exam,         60 limit to pass, min. 10 questions,         time is 60-120 sec/question', max_length=50, verbose_name='exam config')),
                ('exam_types', models.ManyToManyField(blank=True, related_name='units', to='_bases.ExamType', verbose_name='exam types')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='categories.Qualification', verbose_name='qualification')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SkillStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('own_code', models.CharField(max_length=10, verbose_name='own code')),
                ('critical_step', models.BooleanField(default=False, verbose_name='critical step')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillstatements', to='categories.Unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Skill Statement',
                'verbose_name_plural': 'Skill Statements',
                'ordering': ('unit__qualification__code', 'unit', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='categories.Sector', verbose_name='sector'),
        ),
        migrations.CreateModel(
            name='KnowledgeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('own_code', models.CharField(max_length=10, verbose_name='own code')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledgestatements', to='categories.Unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Knowledge Statement',
                'verbose_name_plural': 'Knowledge Statements',
                'ordering': ('unit__qualification__code', 'unit', 'pk'),
            },
        ),
    ]
