# Generated by Django 2.2.6 on 2019-10-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('P1', 'P1'), ('P2', 'P2')], max_length=2, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Exam type',
                'verbose_name_plural': 'Exam types',
                'ordering': ('pk',),
            },
        ),
    ]
